### ISSUE TITLE
Plugin Authoring

### ISSUE THREAD

**Issue by tooolbox** [killbill/kbcli#22]
It's neat to have a Go client library for KB!  I also found the [plugin framework](https://github.com/killbill/killbill-plugin-framework-go) and was a little sad to see it's archived.  I can't post an issue there to ask, but is there a way I can write plugins in Go, for situations where this API client won't suffice?

**Comment by pierre** [comment]
This framework was part of an experiment for plugins written in Go (communicating with Kill Bill over gRPC). We never finished it though as there wasn't a strong demand for it.

Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) in the future for such discussions. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
